### ISSUE TITLE
1293

### ISSUE THREAD

**Issue by rishi-lgtm** [happygirlzt/algorithm-illustrations#1]
https://gist.github.com/rishi-lgtm/cf7d6b0ea7b22cf75f38e5d66986cff3

Optimised code . Please review

**Comment by happygirlzt** [comment]
Hi @rishi-lgtm,
Thanks for your issue! Sorry for the late reply (I did not receive any notification for this issue...)
I updated the [code](https://happygirlzt.com/code/1293.html) based on your suggestion.
Thanks again!

Regards,
happygirlzt
